In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report,ConfusionMatrixDisplay

In [3]:
df=pd.read_csv("Tree_Data.csv")
df

,No,Plot,Subplot,Species,Light_ISF,Light_Cat,Core,Soil,Adult,Sterile,...,AMF,EMF,Phenolics,Lignin,NSC,Census,Time,Event,Harvest,Alive
0,126,1,C,Acer saccharum,0.106,Med,2017,Prunus serotina,I,Non-Sterile,...,22.00,NaN,-0.56,13.86,12.15,4,14.0,1.0,NaN,NaN
1,11,1,C,Quercus alba,0.106,Med,2017,Quercus rubra,970,Non-Sterile,...,15.82,31.07,5.19,20.52,19.29,33,115.5,0.0,NaN,X
2,12,1,C,Quercus rubra,0.106,Med,2017,Prunus serotina,J,Non-Sterile,...,24.45,28.19,3.36,24.74,15.01,18,63.0,1.0,NaN,NaN
3,2823,7,D,Acer saccharum,0.080,Med,2016,Prunus serotina,J,Non-Sterile,...,22.23,NaN,-0.71,14.29,12.36,4,14.0,1.0,NaN,NaN
4,5679,14,A,Acer saccharum,0.060,Low,2017,Prunus serotina,689,Non-Sterile,...,21.15,NaN,-0.58,10.85,11.20,4,14.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2778,7165,17,B,Prunus serotina,0.111,Med,2017,Populus grandidentata,891,Non-Sterile,...,40.89,NaN,0.83,9.15,11.88,16,56.0,1.0,NaN,NaN
2779,7217,17,D,Quercus alba,0.118,Med,2017,Acer rubrum,1468,Non-Sterile,...,15.47,32.82,4.88,19.01,23.50,16,56.0,1.0,NaN,NaN
2780,7306,17,D,Quercus alba,0.118,Med,2017,Quercus rubra,1454,Non-Sterile,...,11.96,37.67,5.51,21.13,19.10,16,56.0,1.0,NaN,NaN
2781,7771,18,D,Quercus alba,0.161,High,2017,Sterile,1297,Sterile,...,16.99,22.51,4.28,19.38,21.36,33,115.5,NaN,NaN,NaN
2782,7401,18,A,Prunus serotina,0.141,High,2016,Populus grandidentata,118,Non-Sterile,...,60.46,NaN,1.00,9.04,11.82,16,56.0,1.0,NaN,NaN

In [4]:
df.isna().sum()

No                0
Plot              0
Subplot           0
Species           0
Light_ISF         0
Light_Cat         0
Core              0
Soil              0
Adult             0
Sterile           0
Conspecific       0
Myco              0
SoilMyco          0
PlantDate         0
AMF               0
EMF            1500
Phenolics         0
Lignin            0
NSC               0
Census            0
Time              0
Event             1
Harvest        2079
Alive          2292
dtype: int64

In [5]:
df.dtypes

No               int64
Plot             int64
Subplot         object
Species         object
Light_ISF      float64
Light_Cat       object
Core             int64
Soil            object
Adult           object
Sterile         object
Conspecific     object
Myco            object
SoilMyco        object
PlantDate       object
AMF            float64
EMF            float64
Phenolics      float64
Lignin         float64
NSC            float64
Census           int64
Time           float64
Event          float64
Harvest         object
Alive           object
dtype: object

In [6]:
df.drop(["EMF", "Harvest", "Alive", "Adult","PlantDate"], axis=1, inplace=True)

In [7]:
lst=["Species","Subplot","Light_Cat","Soil","Sterile","Conspecific","Myco","SoilMyco"]
le=LabelEncoder()
for i in lst:
    df[i]=le.fit_transform(df[i])

In [8]:
df.dtypes

No               int64
Plot             int64
Subplot          int32
Species          int32
Light_ISF      float64
Light_Cat        int32
Core             int64
Soil             int32
Sterile          int32
Conspecific      int32
Myco             int32
SoilMyco         int32
AMF            float64
Phenolics      float64
Lignin         float64
NSC            float64
Census           int64
Time           float64
Event          float64
dtype: object

In [9]:
df.isna().sum()

No             0
Plot           0
Subplot        0
Species        0
Light_ISF      0
Light_Cat      0
Core           0
Soil           0
Sterile        0
Conspecific    0
Myco           0
SoilMyco       0
AMF            0
Phenolics      0
Lignin         0
NSC            0
Census         0
Time           0
Event          1
dtype: int64

In [10]:
df.dtypes

No               int64
Plot             int64
Subplot          int32
Species          int32
Light_ISF      float64
Light_Cat        int32
Core             int64
Soil             int32
Sterile          int32
Conspecific      int32
Myco             int32
SoilMyco         int32
AMF            float64
Phenolics      float64
Lignin         float64
NSC            float64
Census           int64
Time           float64
Event          float64
dtype: object

In [11]:
df.dropna(inplace=True)

In [12]:
df

,No,Plot,Subplot,Species,Light_ISF,Light_Cat,Core,Soil,Sterile,Conspecific,Myco,SoilMyco,AMF,Phenolics,Lignin,NSC,Census,Time,Event
0,126,1,2,0,0.106,2,2017,3,0,1,0,0,22.00,-0.56,13.86,12.15,4,14.0,1.0
1,11,1,2,2,0.106,2,2017,5,0,1,1,1,15.82,5.19,20.52,19.29,33,115.5,0.0
2,12,1,2,3,0.106,2,2017,3,0,1,1,0,24.45,3.36,24.74,15.01,18,63.0,1.0
3,2823,7,3,0,0.080,2,2016,3,0,1,0,0,22.23,-0.71,14.29,12.36,4,14.0,1.0
4,5679,14,0,0,0.060,1,2017,3,0,1,0,0,21.15,-0.58,10.85,11.20,4,14.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2777,7086,17,2,2,0.122,0,2017,5,0,1,1,1,10.89,5.53,21.44,18.99,16,56.0,1.0
2778,7165,17,1,1,0.111,2,2017,2,0,1,0,1,40.89,0.83,9.15,11.88,16,56.0,1.0
2779,7217,17,3,2,0.118,2,2017,0,0,1,1,0,15.47,4.88,19.01,23.50,16,56.0,1.0
2780,7306,17,3,2,0.118,2,2017,5,0,1,1,1,11.96,5.51,21.13,19.10,16,56.0,1.0
2782,7401,18,0,1,0.141,0,2016,2,0,1,0,1,60.46,1.00,9.04,11.82,16,56.0,1.0

In [13]:
x=df.drop(["Sterile"],axis=1)
x

,No,Plot,Subplot,Species,Light_ISF,Light_Cat,Core,Soil,Conspecific,Myco,SoilMyco,AMF,Phenolics,Lignin,NSC,Census,Time,Event
0,126,1,2,0,0.106,2,2017,3,1,0,0,22.00,-0.56,13.86,12.15,4,14.0,1.0
1,11,1,2,2,0.106,2,2017,5,1,1,1,15.82,5.19,20.52,19.29,33,115.5,0.0
2,12,1,2,3,0.106,2,2017,3,1,1,0,24.45,3.36,24.74,15.01,18,63.0,1.0
3,2823,7,3,0,0.080,2,2016,3,1,0,0,22.23,-0.71,14.29,12.36,4,14.0,1.0
4,5679,14,0,0,0.060,1,2017,3,1,0,0,21.15,-0.58,10.85,11.20,4,14.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2777,7086,17,2,2,0.122,0,2017,5,1,1,1,10.89,5.53,21.44,18.99,16,56.0,1.0
2778,7165,17,1,1,0.111,2,2017,2,1,0,1,40.89,0.83,9.15,11.88,16,56.0,1.0
2779,7217,17,3,2,0.118,2,2017,0,1,1,0,15.47,4.88,19.01,23.50,16,56.0,1.0
2780,7306,17,3,2,0.118,2,2017,5,1,1,1,11.96,5.51,21.13,19.10,16,56.0,1.0
2782,7401,18,0,1,0.141,0,2016,2,1,0,1,60.46,1.00,9.04,11.82,16,56.0,1.0

In [14]:
y=df.iloc[:,8]
y

0       0
1       0
2       0
3       0
4       0
       ..
2777    0
2778    0
2779    0
2780    0
2782    0
Name: Sterile, Length: 2782, dtype: int32

In [17]:
from imblearn.over_sampling import RandomOverSampler
sm=RandomOverSampler()
x,y=sm.fit_resample(x,y)

In [18]:
#splitting to test and train data
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=4)

KNeighborsClassifier

In [19]:
knn1=KNeighborsClassifier(algorithm='auto',n_neighbors=9,weights='distance')
knn1.fit(X_train,y_train)
y_pred1=knn1.predict(X_test)
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      0.66      0.79       228
           1       0.76      1.00      0.86       244

    accuracy                           0.83       472
   macro avg       0.88      0.83      0.83       472
weighted avg       0.87      0.83      0.83       472

In [20]:
sv=SVC(C=10, gamma =1, kernel= 'rbf')
sv.fit(X_train,y_train)
y_pred2=sv.predict(X_test)
y_pred2
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       228
           1       1.00      0.99      1.00       244

    accuracy                           1.00       472
   macro avg       1.00      1.00      1.00       472
weighted avg       1.00      1.00      1.00       472

In [21]:
GaussianNB

sklearn.naive_bayes.GaussianNB

In [22]:
nb=GaussianNB()
nb.fit(X_train,y_train)
y_pred2=nb.predict(X_test)
y_pred2
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       228
           1       1.00      1.00      1.00       244

    accuracy                           1.00       472
   macro avg       1.00      1.00      1.00       472
weighted avg       1.00      1.00      1.00       472

DecisionTreeClassifier

In [23]:
dt=DecisionTreeClassifier(criterion='entropy',random_state=2,max_depth=10)
dt.fit(X_train,y_train)
y_pred3=dt.predict(X_test)
y_pred3
print(classification_report(y_test,y_pred3))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       228
           1       1.00      1.00      1.00       244

    accuracy                           1.00       472
   macro avg       1.00      1.00      1.00       472
weighted avg       1.00      1.00      1.00       472

RandomForestClassifier

In [24]:
rf=RandomForestClassifier(criterion= 'entropy', max_depth= None, min_samples_leaf= 1, min_samples_split= 4,n_estimators= 200)
rf.fit(X_train,y_train)
y_pred4=rf.predict(X_test)
y_pred4
print(classification_report(y_test,y_pred4))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       228
           1       1.00      1.00      1.00       244

    accuracy                           1.00       472
   macro avg       1.00      1.00      1.00       472
weighted avg       1.00      1.00      1.00       472

XG BOOST

In [25]:
#xgboost
xgb=XGBClassifier()
xgb.fit(X_train,y_train)
y_pred7=xgb.predict(X_test)
y_pred7
print(classification_report(y_test,y_pred7))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       228
           1       1.00      1.00      1.00       244

    accuracy                           1.00       472
   macro avg       1.00      1.00      1.00       472
weighted avg       1.00      1.00      1.00       472